services:
  crypto_follower_bot:
    container_name: crypto-follower-bot
    working_dir: /crypto_follower_bot
    restart: always
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python bot.py"
